name: ServeRest Cypress E2E & API Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Permissão crucial: Permite que o GitHub Actions escreva na branch do site
permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Fazer o Checkout do Código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar Dependências
        run: npm install

      - name: 🚀 Executar Testes Cypress
        run: npm run test

      - name: 📊 Guardar Relatório (Artifact)
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-mochawesome
          path: cypress/reports/html
          retention-days: 7

      - name: 🌐 Publicar Relatório no GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html