name: ServeRest Cypress E2E & API Tests

# Define os gatilhos: o pipeline corre em cada push ou pull request para a branch main
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Fazer o Checkout do Código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar Dependências
        run: npm install

      - name: 🚀 Executar Testes Cypress
        run: npm run test

      - name: 📊 Guardar Relatório (Artifact)
        # if always é crucial para que o relatório seja gerado e guardado
        # mesmo que algum teste falhe durante a execução.
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-mochawesome
          path: cypress/reports/html
          retention-days: 7